### ISSUE TITLE
Ability to get number of "pending" items in queue

### ISSUE THREAD

**Issue by holtkamp** [clue/reactphp-mq#12]
Currently it seems not possible to determine the amount of "pending" items in the queue. 

https://github.com/clue/reactphp-mq/blob/118aede68865a42a5e876eb020e506c4ab5c4f79/src/Queue.php#L29

Would it be possible to add a getter?

```php
    public function getPending(): int
    {
        return $this->pending;
    }
```

**Comment by clue** [comment]
Thank you for bringing up this suggestion! I'm not opposed to this idea, but maybe you care to elaborate what's your use case? :+1:

**Comment by holtkamp** [comment]
Sure! I am working on https://github.com/dpovshed/octopus/issues/17

Having access to the amount of pending tasks would be useful for the following parts:

- determine whether all work is done, so we can stop the timers, essentially: `$queue->count() + $queue->pending() === 0`
- display statistics to the user: `$numberOfItemsToProcess / $numberOfItemsBeingProcessed / $numberOfItemsCompleted

**Comment by clue** [comment]
You can actually `count()` the queue to get the number of outstanding jobs (currently active ones plus queued ones):

```php
$queue = new Queue(2, null, $handler);
$queue('a');
$queue('b');
$queue('c');

$loop->addPeriodicTimer(1.0, function () use ($queue) {
    echo 'Still outstanding: ' . count($queue) . PHP_EOL;
});
```

The queue does not currently offer a way to get its concurrency parameter as passed to its constructor. But because this is an immutable value, you can also reference this variable in your consumer code like this:

```php
$concurrency = 2;
$queue = new Queue($concurrency, null, $handler);

$loop->addPeriodicTimer(1.0, function () use ($queue, $concurrency) {
    // active: number of jobs capped at concurrency limit
    $total = count($queue);
    $active = $total > $concurrency ? $concurrency : $total;

    // queued: number of jobs minus active ones
    $queued = $total - $active;
//  $queued = $total > $concurrency ? ($total - $concurrency) : 0;

    echo 'Currently ' . $active . ' active plus ' . $queued . ' queued' . PHP_EOL;
});
```

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by holtkamp** [comment]
thanks for the response

>The queue does not currently offer a way to get its concurrency parameter as passed to its constructor. But because this is an immutable value, you can also reference this variable in your consumer code.

Thanks, that is exactly what I decided to do. However the "allowed concurrency" does not particularly equal the "currently applied concurrency". Especially when a high concurrency is used (let's say 100) and the queue is almost done, then the number of active items should count down:

- 100
- 99
- 98
- ..
- 3
- 2
- 1
- done!

Not a big deal that the number of active items is not tracked, was more of a "nice to have" 😄

**Comment by clue** [comment]
> However the "allowed concurrency" does not particularly equal the "currently applied concurrency". Especially when a high concurrency is used (let's say 100) and the queue is almost done, then the number of active items should count down:

I'm not sure I follow. The `Queue` will always process the next job once one of the pending jobs is completed. This means that it is guaranteed to always keep `N` jobs running at a given time (`N` being the concurrency parameter), provided there are still enough jobs in the queue. This implies that if the queue drains and you eventually run out of jobs, the number of active jobs decrease until the last job is completed, at which point this should report zero active jobs.

**Comment by holtkamp** [comment]
> provided there are still enough jobs in the queue. This implies that if the queue drains and you eventually run out of jobs, the number of active jobs decrease until the last job is completed

indeed, this is what I meant. When looking better at your example, you take this "draining" into account (Y).

My question is answered, thanks for diving into this!
